chore: Add label github actions
EasyMile/postgresql-operator pull request #3
Opened 2020-02-24 15:52 UTC by AlexDouze

2020-02-24 16:34 UTC, oxyno-zeta approved these changes

2020-02-24 17:46 UTC, oxyno-zeta approved these changes

2020-02-24 17:46 UTC, oxyno-zeta requested changes

2020-02-24 17:46 UTC, oxyno-zeta commented on .github/labeler.yml
> +  - .github/labeler.yml
No star for files in it ?

2020-02-25 09:09 UTC, AlexDouze commented on .github/labeler.yml
> +  - .github/labeler.yml
Indeed

2020-02-25 09:16 UTC, oxyno-zeta approved these changes

2020-02-25 09:16 UTC, merged